POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name" : "Eko",
  "id": "eko",
  "password": "eko"
}

###

POST http://localhost:3000/api/users/_login
Content-Type: application/json

{
  "id": "eko",
  "password": "eko"
}

###

GET http://localhost:3000/api/hello
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmUiOjE3NTY3MjA2ODExODAsImlkIjoiZWtvIn0.5p-1fMk8uHqU0n6Z_QDZsS1zaCu5I5D0jJT6_Ad3WgM