POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name" : "Taufiq Vhunakoshi",
  "id": "vhunakoshi",
  "password": "password123"
}

###

POST http://localhost:3000/api/users/_login
Content-Type: application/json

{
  "id": "vhunakoshi",
  "password": "password123"
}

###

GET http://localhost:3000/api/hello
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmUiOjE3NTcyMzUwMjc1OTYsImlkIjoidmh1bmFrb3NoaSJ9.Pd3NMUF2FfaavefUlV_1NWaRTW36xRP-L2C8uOXdG88